version: 4.2.{build}
image: Visual Studio 2017


environment:
  matrix:
  - PlatformToolset: v141

platform:
    - x64
    - Win32

configuration:
    - Release
    - Debug

install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="x64" set platform_input=x64

    - if "%platform%"=="Win32" set archi=x86
    - if "%platform%"=="Win32" set platform_input=Win32

    - if "%PlatformToolset%"=="v141" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%


build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"\curl\winbuild
    - if "%configuration%"=="Debug" set debugflag=yes
    - if "%configuration%"=="Release" set debugflag=no
    - nmake /f Makefile.vc mode=dll vc=15 RTLIBCFG=static DEBUG="%debugflag%" 

    - cd "%APPVEYOR_BUILD_FOLDER%"\vcproj
    - msbuild GUP.vcxproj /m /p:configuration="%configuration%" /p:platform="%platform_input%" /p:PlatformToolset="%PlatformToolset%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"\
    - ps: >-

        if ($env:PLATFORM_INPUT -eq "x64" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "bin64\GUP.exe" -FileName GUP.exe
            Push-AppveyorArtifact curl\builds\libcurl-vc15-x64-release-dll-ipv6-sspi-schannel\bin\libcurl.dll -FileName libcurl.dll
        }

        if ($env:PLATFORM_INPUT -eq "Win32" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "bin\GUP.exe" -FileName GUP.exe
            Push-AppveyorArtifact curl\builds\libcurl-vc15-x86-release-dll-ipv6-sspi-schannel\bin\libcurl.dll -FileName libcurl.dll
        }

